### ISSUE TITLE
screenshot

### ISSUE THREAD

**Issue by iamcco** [iamcco/coc-actions#1]
![](https://user-images.githubusercontent.com/5492542/71774253-78717700-2fa6-11ea-9629-1e88d0b5114e.png)

**Comment by nayaabkhan** [comment]
Hi @iamcco! Nice `colorscheme`. What is it?

**Comment by iamcco** [comment]
@nayaabkhan gruvbox-material

**Comment by oswaldoo** [comment]
Hi @iamcco ,

what font do you use?

**Comment by iamcco** [comment]
The font is Fantasque sans


---Original---
