### ISSUE TITLE
How to install with vim-plug

### ISSUE THREAD

**Issue by Avi-D-coder** [iamcco/coc-actions#13]
`Plug 'iamcco/coc-actions', {'do': 'yarn install'}`
Does not work

**Comment by iamcco** [comment]
yarn build after install: `Plug 'iamcco/coc-actions', {'do': 'yarn install && yarn build'}`

**Comment by Avi-D-coder** [comment]
It sort of works when I enter `:CocCommand actions.open`, but the config from the readme is broken. `\aw` just acts like `w` and replacing `<leader>a` with another unbound key does not fix it.

**Comment by iamcco** [comment]
> \aw just acts like w and replacing <leader>a with another unbound key does not fix it.

I don't know what does it means

**Comment by Avi-D-coder** [comment]
Replacing `<leader>a` with another key (E.g `<F1>`) does not fix the issue.
The mappings are broken.

```vim
xmap <silent> <F1> :<C-u>execute 'CocCommand actions.open ' . visualmode()<CR>
nmap <silent> <F1> :<C-u>set operatorfunc=<SID>cocActionsOpenFromSelected<CR>g@
```

**Comment by iamcco** [comment]
Can't reproduce, checkout doc of vim `:h ext-objects`

**Comment by Avi-D-coder** [comment]
I thought it might be `kana/vim-textobj-user` messing things up, but no luck.

**Comment by Avi-D-coder** [comment]
It a more general issue. The following is broken. There are no conflicting mappings. And manually executing ` :CocCommand actions.open` works.
```vim
vmap <F1> :CocCommand actions.open<CR>
nmap <F1> :CocCommand actions.open<CR>
```

**Comment by iamcco** [comment]
> I thought it might be kana/vim-textobj-user messing things up, but no luck.

It's no related to `kana/vim-textobj-user`, `text-objects` is built-in of vim.

> It a more general issue. The following is broken. There are no conflicting mappings. And manually executing :CocCommand actions.open works.
>
>```
>vmap <F1> :CocCommand actions.open<CR>
>nmap <F1> :CocCommand actions.open<CR>
>```

Can't help, it works for me, try minvimrc or checkout your mapping.

**Comment by Avi-D-coder** [comment]
Thanks, I figured it out.

**Comment by ELLIOTTCABLE** [comment]
It would be nice to indicate that the usual `yarn install --frozen-lockfile` isn't enough in the README — out of about a dozen coc extensions I have installed via `vim-plug`, this is the only one that didn't work without the extra step.

Would have saved me a lot of time! <3
