### ISSUE TITLE
Visual mode mapping for preexisting selection?

### ISSUE THREAD

**Issue by Avi-D-coder** [iamcco/coc-actions#14]
Say I wanted to select text and then open actions on the selected text.
Noun verb instead of the verb noun mapping from the readme.

This seems to work do I need anything else?
`vnoremap <silent> <F1> :<C-u>CocCommand actions.open<CR>`

**Comment by iamcco** [comment]
Use `vnoremap <silent> <F1> :<C-u>execute 'CocCommand actions.open ' . visualmode()<CR>` instead.
