### ISSUE TITLE
Cyclical Menu

### ISSUE THREAD

**Issue by yutkat** [iamcco/coc-actions#18]
I use coc-actions a lot, but I don't really like the behavior of the menu not being able to move to cyclic.

Is it possible for the bottom candidate to be selected when I press the `<Ctrl-p>` or `<Up>` key while the cursor is on the top candidate?

I think this is very useful for adding words to the dictionary.　It will behave the same way as the vim's completion menu.

---

I would be happy to consider and respond to you.

**Comment by iamcco** [comment]
It is a normal buffer. Ctrl+G can goto the bottom and gg to the top. I thinks you can set mapping like that.

**Comment by yutkat** [comment]
Really?
It works, Thank you. It's very useful!
