### ISSUE TITLE
Possible to avoid whitespaces in menu?

### ISSUE THREAD

**Issue by oblitum** [iamcco/coc-actions#3]
I use a trailing whitespace plugin, which is causing coc-actions floating windows to get ugly. I've opened this issue in their repo, but maybe this can also be avoided from this side?

https://github.com/ntpeters/vim-better-whitespace/issues/125

**Comment by iamcco** [comment]
Should be bug of `ntpeters/vim-better-whitespace`, It should not highlight when `&buftype='nofile'`.

**Comment by oblitum** [comment]
The check is present already but for some reason it doesn't work.

**Comment by oblitum** [comment]
https://github.com/ntpeters/vim-better-whitespace/blob/master/plugin/better-whitespace.vim#L123

**Comment by iamcco** [comment]
If do not use the tail white space, i need to find a way to highlight the active line.

**Comment by oblitum** [comment]
I see.

I've tried to add `cocactions` to the `g:better_whitespace_filetypes_blacklist`, but it simply doesn't work. I'm not sure why it doesn't work, it's like `&filetype` and `&buftype` is being ignored for the floating window, or maybe for the plugin it's getting the type for the parent buffer, not the float.

**Comment by oblitum** [comment]
@iamcco I have another unrelated problem with coc-actions, I have setup mappings just like in the README, but when I trigger the normal mode mapping, I don't get the actions menu, I need to press next (`<c-n>`), for it to show, otherwise it's not displayed.

**Comment by oblitum** [comment]
Ah, following README, it does display for `<leader>aw`, etc, after I type `w`, but for simply `<leader>a`, it does not.

**Comment by oblitum** [comment]
Ah, scratch that. Now I know how that part works. It's working.

**Comment by oblitum** [comment]
> If do not use the tail white space, i need to find a way to highlight the active line.

What about setting `cursorline` and `hi CursorLine` locally for the floating window? (I even thought it was being done with that already).

**Comment by iamcco** [comment]
I had added option `coc-actions.useCursorLine: true` to use cursorLine. But It's style is same with normal window's cursorLine, because `set winhighlight=CursorLine:PmenuSel` seems no effect.

**Comment by oblitum** [comment]
@iamcco nice thanks, it avoids the issue, but may be weird depending on colorscheme.

I have noticed now that after coc-actions 1.2.0 I'm getting a wider float with `[-]`, and other sections. Is there an option to disable that? I prefer the more compact menus, it cover less code.

**Comment by iamcco** [comment]
use `coc-actions.showActionKind: fslse` to hide the kind

**Comment by oblitum** [comment]
Thanks!

**Comment by oblitum** [comment]
>  but may be weird depending on colorscheme

By that I mean it looks like reverse selection in the colorscheme I'm using. But it's better than the red whitespace.

**Comment by iamcco** [comment]
wait for neovim fix https://github.com/neovim/neovim/issues/11778

**Comment by oblitum** [comment]
Nice.
