### ISSUE TITLE
Menu does not appear until clicking down key (`j`)

### ISSUE THREAD

**Issue by kevholder** [iamcco/coc-actions#9]
When I click `<leader> a` the cursor disappears but the menu doesn't show up until I go down with `j`. Is this normal? Any way to get the menu to appear automatically?

![tvK6bAeLMP](https://user-images.githubusercontent.com/60701112/78806299-785f8980-7990-11ea-9605-68eea6561dfe.gif)

**Comment by iamcco** [comment]
![image](https://user-images.githubusercontent.com/5492542/78809094-f8b9d500-79f8-11ea-8b11-211dd5a49fee.png)

**Comment by kevholder** [comment]
Thanks. Is it ppossible to map `<leader>a` to do the same as `<leader>aw` ?

**Comment by iamcco** [comment]
You should do your own mapping.

**Comment by kevholder** [comment]
Yes I know. Do you know what mapping will do it?

**Comment by iamcco** [comment]
map to `:CocCommand actions.open`
